### ISSUE TITLE
when i run this py,some wrong,can you help me

### ISSUE THREAD

**Issue by tianxia007** [Js-Mim/mss_pytorch#12]
C:\Users\hasee\AppData\Local\Programs\Python\Python36\python.exe C:/projects_openproject/mss_pytorch/processes_scripts/main_script.py
Traceback (most recent call last):
  File "C:/projects_openproject/mss_pytorch/processes_scripts/main_script.py", line 6, in <module>
    import torch
  File "C:\Users\hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的模块。

can you provide more detail introduction to help us run this project ,thanks

**Comment by dr-costas** [comment]
Hi, 

As you can see from the line: 

> File "C:\Users\hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_init_.py", line 78

The problem appears at the files of PyTorch. I guess that the install of PyTorch did not went as expected for your system. 

To test that, I would suggest to you to create a simple file and try to do something with PyTorch. e.g. 

```python
import torch

x = torch.rand(3, 4)
print(x)
```

**Comment by tianxia007** [comment]
@dr-costas hi,when i has install anaconda,i hava resolve last problem.
now,show those wrong:
C:\Users\hasee\Anaconda3\python.exe C:/projects_openproject/music_deal/processes_scripts/main_script.py
Exception in user code:
Traceback (most recent call last):
------------------------------------------------------------
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\hasee\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\hasee\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\hasee\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\hasee\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\hasee\Anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000027E4E9CD630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\hasee\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E4E9CD630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hasee\Anaconda3\lib\site-packages\visdom\__init__.py", line 446, in _send
    data=json.dumps(msg),
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E4E9CD630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
------------   Building model   ------------
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:49: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(self.gruEncF.weight_hh)
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:50: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  nn.init.xavier_normal(self.gruEncF.weight_ih)
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:54: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(self.gruEncB.weight_hh)
Initialization of the encoder done...
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:55: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  nn.init.xavier_normal(self.gruEncB.weight_ih)
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:141: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(self.gruDec.weight_hh)
Initialization of the decoder done...
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:142: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
Initialization of the sparse decoder done...
  nn.init.xavier_normal(self.gruDec.weight_ih)
C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py:215: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  nn.init.xavier_normal(self.ffDec.weight)
Traceback (most recent call last):
  File "C:/projects_openproject/music_deal/processes_scripts/main_script.py", line 180, in <module>
    sfiltnet = main(training, apply_sparsity)
  File "C:/projects_openproject/music_deal/processes_scripts/main_script.py", line 54, in main
    source_enhancement = s_s_net.SourceEnhancement(B, T, N, F, L)
  File "C:\projects_openproject\music_deal\modules\cls_sparse_skip_filt.py", line 267, in __init__
    self.ffSe_enc = nn.Linear(self._N, self._N/2)
  File "C:\Users\hasee\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 41, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!)


Process finished with exit code 1

what is reason,and how to deal ,Thanks in advance for your response :)

**Comment by tianxia007** [comment]
and   this program can deal Chinese song?😀

**Comment by Js-Mim** [comment]
Hi @tianxia007,

for the first errors if i understand them correctly they come from the visdom package.
Please make sure that you have installed visdom version 0.1.5 and urllib version 1.17.
As for the pytorch errors i think you are using different version. For this work we used pytorch 0.3.0.post4.

We have not tested much with non-western music. Let us know if it does the job in Chinese music :) .

**Comment by tianxia007** [comment]
thanks!!😀
