### ISSUE TITLE
I cant run this project, please help me

### ISSUE THREAD

**Issue by suntingfeng** [Js-Mim/mss_pytorch#13]
Hi, I run this project with the following error:
Traceback (most recent call last):
  File "D:/py_item/mss_pytorch-master/mss_pytorch-master/processes_scripts/main_script.py", line 191, in <module>
    nnet_helpers.test_nnet(sfiltnet, 60, 10*2, 2049, 4096, 384, 16)
  File "D:\py_item\mss_pytorch-master\mss_pytorch-master\helpers\nnet_helpers.py", line 302, in test_nnet
    H_enc = nnet[0](mx[batch * B: (batch+1)*B, :, :])
  File "C:\Users\19052195\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\py_item\mss_pytorch-master\mss_pytorch-master\modules\cls_sparse_skip_filt.py", line 86, in forward
    h_t_fr = self.gruEncF((cxin[:, t, :]), h_t_fr)
  File "C:\Users\19052195\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\19052195\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\rnn.py", line 970, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #4 'mat1'

My python version is Python 3.5.2
this project is developed baesd on python 2 ?

**Comment by bourbonkk** [comment]
me too.. same error

**Comment by dr-costas** [comment]
Hi, 

As you can see, the error is at the PyTorch code for forward passing at RNNs: 

`File "C:\Users\19052195\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\rnn.py`

The problem is caused due to the types of the variables. Chances are that your input variable to the module is `Double` instead of `Float`. 

What you can do, is to go to the line where the mixture is given to the first layer and add the `.float()`.

**Comment by bourbonkk** [comment]
> Hi,
> 
> As you can see, the error is at the PyTorch code for forward passing at RNNs:
> 
> `File "C:\Users\19052195\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\modules\rnn.py`
> 
> The problem is caused due to the types of the variables. Chances are that your input variable to the module is `Double` instead of `Float`.
> 
> What you can do, is to go to the line where the mixture is given to the first layer and add the `.float()`.

I'm sorry, but can you tell me a little bit more about which parts to modify?

**Comment by dr-costas** [comment]
You have to cast the input variable to the model from Double to Float.

**Comment by suntingfeng** [comment]
Thank you, this problem has beed solved.
I have another question. I use your test.wav to test the effect very well, the BGM basically disappears.
But I use Chinese songs for testing and the effect is very poor.
Does it support Chinese songs? Or how should I adjust the parameters?
Thank you!
